#define ARQLIVRO "files/livros.csv"
#define ARQLIVROTEMP "files/livros_temp.csv"
#define ARQUSUARIO "files/usuarios.csv"
#define ARQUSUARIOTEMP "files/usuarios_temp.csv"
#define ARQALUGUEL "files/alugueis.csv"
#define ARQALUGUELTEMP "files/alugueis_temp.csv"
